CREATE PLUGGABLE DATABASE ka_pdb_29077
ADMIN USER KAYITESI_plsqlauca_29077
IDENTIFIED BY YourPassword123
FILE_NAME_CONVERT = (
    'C:\APP\USER\PRODUCT\21C\ORADATA\XE\PDBSEED\',
    'C:\APP\USER\PRODUCT\21C\ORADATA\XE\KA_PDB_29077\'
);
ALTER PLUGGABLE DATABASE ka_pdb_29077 OPEN;

SHOW PDBS;

ALTER PLUGGABLE DATABASE ka_pdb_29077 SAVE STATE;


SELECT NAME, OPEN_MODE
FROM V$PDBS
WHERE NAME = 'KA_PDB_29077';

ALTER SESSION SET CONTAINER = ka_pdb_29077;

SHOW CON_NAME;

SELECT USERNAME
FROM DBA_USERS
WHERE USERNAME = 'KAYITESI_PLSQLAUCA_29077';


SHOW PDBS;

ALTER SESSION SET CONTAINER = CDB$ROOT;

SHOW CON_NAME;


CREATE PLUGGABLE DATABASE ka_to_delete_pdb_29077
ADMIN USER KAYITESI_plsqlauca_29077
IDENTIFIED BY YourPassword123
FILE_NAME_CONVERT = (
    'C:\APP\USER\PRODUCT\21C\ORADATA\XE\PDBSEED\',
    'C:\APP\USER\PRODUCT\21C\ORADATA\XE\KA_TO_DELETE_PDB_29077\'
);

SHOW PDBS;

ALTER PLUGGABLE DATABASE ka_to_delete_pdb_29077 OPEN;


ALTER PLUGGABLE DATABASE ka_to_delete_pdb_29077 CLOSE IMMEDIATE;

DROP PLUGGABLE DATABASE ka_to_delete_pdb_29077 INCLUDING DATAFILES;

SHOW PDBS;

SHOW PDBS;

SELECT NAME, OPEN_MODE
FROM V$PDBS
WHERE NAME = 'KA_TO_DELETE_PDB_29077';


ALTER SESSION SET CONTAINER = CDB$ROOT;

SELECT DBMS_XDB_CONFIG.GETHTTPSPORT() AS HTTPS_PORT
FROM DUAL;

